services:
  db:
    image: mysql:8.4
    container_name: database-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hospital
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
