name: Run Spring Boot Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [21]
        gradle-version: [8.8]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java-version }}

    - name: Set up Gradle ${{ matrix.gradle-version }}
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: ${{ matrix.gradle-version }}

    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ matrix.java-version }}-${{ matrix.gradle-version }}
        restore-keys: |
          gradle-${{ runner.os }}-${{ matrix.java-version }}

    - name: Run tests
      run: ./gradlew test
